return table.freeze({
	ClassIds = require(script.ClassIds),
	GradeIds = require(script.GradeIds),
	FighterCombatSnapshot = require(script.FighterCombatSnapshot),
	FighterMilestones = require(script.FighterMilestones),
	FighterProjector = require(script.FighterProjector),
	FighterComparison = require(script.FighterComparison),
	FighterProgression = require(script.FighterProgression),
	FighterExperienceCalculator = require(script.FighterExperienceCalculator),
})
