return table.freeze({
	CombatantKinds = require(script.CombatantKinds),
	CombatActionTypes = require(script.CombatActionTypes),
	CombatActionResultOutcomes = require(script.CombatActionResultOutcomes),
	EncounterOutcomes = require(script.EncounterOutcomes),
	CombatantRef = require(script.CombatantRef),
	CombatAction = require(script.CombatAction),
	CombatActionResult = require(script.CombatActionResult),
	EncounterResult = require(script.EncounterResult),
})
