return table.freeze({
	CombatantKinds = require(script.CombatantKinds),
	CombatActionTypes = require(script.CombatActionTypes),
	CombatActionResultOutcomes = require(script.CombatActionResultOutcomes),
	EncounterOutcomes = require(script.EncounterOutcomes),
	CombatantRef = require(script.CombatantRef),
	CombatAction = require(script.CombatAction),
	CombatActionResult = require(script.CombatActionResult),
	CombatJournalEntryKinds = require(script.CombatJournalEntryKinds),
	CombatJournalEntry = require(script.CombatJournalEntry),
	EncounterResult = require(script.EncounterResult),
	Simulation = require(script.Simulation),
})
